name: libfuzzer
arch:
  amd64:
    build_args:
      - IMAGE=mozillasecurity/fuzzos:amd64-latest
  arm64:
    build_args:
      - IMAGE=mozillasecurity/fuzzos:arm64-latest
manifest: ./scripts/docker-manifest.sh mozillasecurity libfuzzer
